### ISSUE TITLE
Generated Reports gives ErrorException

### ISSUE THREAD

**Issue by Ezyweb-uk** [LaravelDaily/Laravel-Import-CSV-Chart.js-Reports#1]
All links under Generated Reports are giving me the following error:

> Undefined variable: reports (View: <_mypath_>\resources\views\admin\reports.blade.php)

**Comment by PovilasKorop** [comment]
@Ezyweb-uk thanks, fixed: https://github.com/LaravelDaily/Laravel-Import-CSV-Chart.js-Reports/commit/e16f7404568409d94d1371f493149489fa4c98bb
